# Generated by Django 4.2.1 on 2025-06-10 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPSARun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_type', models.CharField(choices=[('BULK', 'BULK'), ('BATCHED', 'BATCHED')], max_length=16)),
                ('distribution_type', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MULTIPLE', 'MULTIPLE')], max_length=16)),
                ('alpha', models.FloatField()),
                ('gamma', models.FloatField()),
                ('iterations', models.IntegerField()),
                ('pairs_per', models.IntegerField()),
                ('a_ratio', models.FloatField()),
                ('a_value', models.FloatField()),
                ('tune', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spsa_run', to='OpenBench.test')),
            ],
        ),
        migrations.CreateModel(
            name='SPSAParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('is_float', models.BooleanField()),
                ('start', models.FloatField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('c_end', models.FloatField()),
                ('r_end', models.FloatField()),
                ('c_value', models.FloatField()),
                ('a_end', models.FloatField()),
                ('a_value', models.FloatField()),
                ('spsa_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='OpenBench.spsarun')),
            ],
        ),
    ]
