# Generated by Django 4.2.1 on 2025-06-10 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0002_spsarun_spsaparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spsaparameter',
            name='spsa_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='OpenBench.spsarun'),
        ),
    ]
