# Generated by Django 4.2.1 on 2025-06-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0003_alter_spsaparameter_spsa_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='spsaparameter',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
