# Generated by Django 4.2.1 on 2026-01-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0004_spsaparameter_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spsaparameter',
            name='a_end',
        ),
        migrations.RemoveField(
            model_name='spsarun',
            name='a_value',
        ),
    ]
