# Generated by Django 4.2.1 on 2026-01-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0006_auto_20260126_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='spsa',
        ),
    ]
