# Generated by Django 4.2.1 on 2026-04-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0007_remove_test_spsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='games',
            field=models.BigIntegerField(default=0),
        ),
    ]
