# Generated by Django 4.2.1 on 2026-06-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0008_alter_profile_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='info',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
