# Generated by Django 4.2.1 on 2026-06-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0009_test_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='awaiting',
        ),
    ]
