# Generated by Django 4.2.1 on 2026-09-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0013_nps_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
    ]
