# Generated by Django 4.2.1 on 2026-09-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0015_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('private', models.BooleanField(default=False)),
                ('nps', models.IntegerField(default=0)),
                ('source', models.CharField(max_length=1024)),
                ('enabled', models.BooleanField(default=True)),
                ('build_path', models.CharField(blank=True, max_length=64)),
                ('build_compilers', models.CharField(blank=True, max_length=64)),
                ('build_cpuflags', models.CharField(blank=True, max_length=64)),
                ('build_systems', models.CharField(blank=True, max_length=64)),
                ('presets', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ServerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_checksum', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
